# Generated by Django 3.0.5 on 2020-05-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0002_dealership_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
