# Generated by Django 3.0.5 on 2020-04-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CU', 'Customer'), ('DE', 'Dealership Admin'), ('MA', 'Manufacturer Admin')], default='CU', max_length=2),
        ),
    ]
