# Generated by Django 3.0.5 on 2020-04-30 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0002_dealership_admin'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaledeal',
            name='dealership_admin',
        ),
        migrations.AddField(
            model_name='wholesaledeal',
            name='dealership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealerships.Dealership'),
        ),
        migrations.AlterField(
            model_name='wholesaledeal',
            name='status',
            field=models.CharField(choices=[('PE', 'PENDING'), ('AC', 'ACCEPTED'), ('RE', 'REJECTED')], default='PE', max_length=2),
        ),
    ]
