# Generated by Django 3.0.5 on 2020-05-01 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200430_0059'),
        ('deals', '0002_auto_20200430_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaledeal',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.WholesaleCar'),
        ),
    ]
