# Generated by Django 3.0.5 on 2020-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_retaildeal_asking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaledeal',
            name='asking_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
