# Generated by Django 3.0.5 on 2020-04-29 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprints', '0003_car_wholesale'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprints.Car')),
            ],
        ),
    ]
