# Generated by Django 3.0.5 on 2020-05-01 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0002_dealership_admin'),
        ('inventory', '0002_auto_20200430_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.WholesaleCar')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealerships.Dealership')),
            ],
        ),
    ]
