# Generated by Django 3.0.5 on 2020-05-01 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0002_dealership_admin'),
        ('inventory', '0003_retailcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailcar',
            name='dealership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealerships.Dealership'),
        ),
    ]
