# Generated by Django 3.0.5 on 2020-05-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200502_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailcar',
            old_name='selling_price',
            new_name='retail_price',
        ),
        migrations.RenameField(
            model_name='wholesalecar',
            old_name='selling_price',
            new_name='wholesale_price',
        ),
    ]
