# Generated by Django 3.0.5 on 2020-04-29 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturers', '0002_manufacturingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
