# Generated by Django 3.0.5 on 2020-04-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0003_manufacturer_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
