# Generated by Django 3.0.5 on 2020-05-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0004_auto_20200429_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
