# Generated by Django 3.0.5 on 2020-05-02 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0006_auto_20200502_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='balance',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
