# Generated by Django 3.0.5 on 2020-05-02 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0007_auto_20200502_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='balance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
