# Generated by Django 3.0.5 on 2020-05-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0008_auto_20200502_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturers.Manufacturer'),
        ),
    ]
