# Generated by Django 3.0.5 on 2020-05-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0003_car_wholesale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='wholesale',
        ),
    ]
