# Generated by Django 3.0.5 on 2020-05-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0009_manufacturingorder_manufacturer'),
        ('blueprints', '0004_remove_car_wholesale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturers.Manufacturer'),
        ),
    ]
